METRIC_FIELDS = [
    "green_area",
    "lighting",
    "traffic",
    "air_quality",
    "walkability",
    "accessibility",
    "safety",
    "heat",
    "mobility",
    "eco_score",
    "population_density",
    "noise_level",
    "public_transport_access",
    "barrier_level",
    "housing_capacity",
    "housing_pressure",
    "economic_activity",
    "commercial_access",
    "social_service_access",
    "healthcare_access",
    "education_access",
    "utility_network_load",
    "infrastructure_stability",
    "service_capacity",
    "attractiveness_score",
    "livability_score",
    "employment_support",
    "public_space_quality",
    "environmental_resilience",
]

POSITIVE_METRICS = {
    "green_area": 0.06,
    "lighting": 0.04,
    "air_quality": 0.06,
    "walkability": 0.06,
    "accessibility": 0.06,
    "safety": 0.08,
    "mobility": 0.05,
    "eco_score": 0.05,
    "public_transport_access": 0.04,
    "housing_capacity": 0.05,
    "economic_activity": 0.06,
    "commercial_access": 0.04,
    "social_service_access": 0.05,
    "healthcare_access": 0.04,
    "education_access": 0.04,
    "infrastructure_stability": 0.06,
    "service_capacity": 0.05,
    "attractiveness_score": 0.04,
    "livability_score": 0.07,
    "employment_support": 0.03,
    "public_space_quality": 0.04,
    "environmental_resilience": 0.04,
}

NEGATIVE_METRICS = {
    "traffic": 0.05,
    "heat": 0.04,
    "noise_level": 0.03,
    "barrier_level": 0.03,
    "housing_pressure": 0.05,
    "utility_network_load": 0.05,
}

ACTION_DEFINITIONS = {
    "add_park": {
        "delta": {
            "green_area": 20,
            "air_quality": 8,
            "eco_score": 12,
            "attractiveness_score": 10,
            "livability_score": 9,
            "public_space_quality": 12,
            "environmental_resilience": 6,
            "social_service_access": 2,
            "heat": -10,
            "noise_level": -5,
        },
        "downsides": [
            "May require land allocation in dense or road-dominated areas.",
            "Maintenance and watering costs may increase.",
        ],
    },
    "add_lighting": {
        "delta": {
            "lighting": 20,
            "safety": 15,
            "accessibility": 5,
            "walkability": 6,
            "livability_score": 5,
            "attractiveness_score": 3,
        },
        "downsides": [
            "Energy and maintenance costs increase.",
            "If poorly placed, lighting can create light pollution near homes.",
        ],
    },
    "add_bike_lane": {
        "delta": {
            "mobility": 12,
            "eco_score": 6,
            "traffic": -5,
            "safety": 2,
            "walkability": 2,
            "attractiveness_score": 3,
            "livability_score": 3,
            "environmental_resilience": 2,
        },
        "downsides": [
            "In narrow streets, road space competition may create implementation friction.",
            "Requires safe design to avoid conflicts with cars and pedestrians.",
        ],
    },
    "add_ramp": {
        "delta": {
            "accessibility": 20,
            "barrier_level": -15,
            "walkability": 3,
            "livability_score": 4,
        },
        "downsides": [
            "Retrofit cost may be higher in older infrastructure.",
        ],
    },
    "add_bus_stop": {
        "delta": {
            "public_transport_access": 20,
            "mobility": 10,
            "traffic": -3,
            "walkability": 3,
            "commercial_access": 3,
            "social_service_access": 3,
            "livability_score": 3,
        },
        "downsides": [
            "If too many stops are close together, route speed may decrease.",
            "Requires placement that does not block key traffic flow points.",
        ],
    },
    "reduce_traffic": {
        "delta": {
            "traffic": -15,
            "eco_score": 8,
            "safety": 4,
            "noise_level": -6,
            "air_quality": 5,
            "heat": -2,
            "livability_score": 5,
            "attractiveness_score": 3,
            "environmental_resilience": 3,
        },
        "downsides": [
            "May require stricter traffic management or rerouting.",
        ],
    },
    "remove_barriers": {
        "delta": {
            "barrier_level": -20,
            "accessibility": 15,
            "walkability": 4,
            "safety": 2,
            "livability_score": 4,
        },
        "downsides": [
            "Can require redesign of curb edges and path geometry.",
        ],
    },
    "add_pedestrian_crossing": {
        "delta": {
            "safety": 12,
            "walkability": 8,
            "accessibility": 4,
            "traffic": -2,
            "livability_score": 3,
        },
        "downsides": [
            "Vehicle throughput may slow slightly at peak hours.",
        ],
    },
    "add_public_benches": {
        "delta": {
            "walkability": 5,
            "accessibility": 3,
            "safety": 1,
            "public_space_quality": 6,
            "livability_score": 4,
            "attractiveness_score": 2,
        },
        "downsides": [
            "Requires maintenance and thoughtful placement.",
        ],
    },
    "add_waste_bins": {
        "delta": {
            "eco_score": 5,
            "walkability": 2,
            "air_quality": 1,
            "public_space_quality": 3,
            "livability_score": 2,
        },
        "downsides": [
            "Needs regular collection to avoid overflow.",
        ],
    },
    "add_residential_building": {
        "delta": {
            "housing_capacity": 18,
            "housing_pressure": -10,
            "economic_activity": 4,
            "service_capacity": -3,
            "traffic": 6,
            "utility_network_load": 8,
            "heat": 4,
            "infrastructure_stability": -4,
            "attractiveness_score": 2,
        },
        "downsides": [
            "Can overload utilities and services if support infrastructure lags behind.",
            "Additional traffic and heat stress may appear in already dense zones.",
        ],
    },
    "add_commercial_building": {
        "delta": {
            "economic_activity": 16,
            "commercial_access": 14,
            "employment_support": 12,
            "attractiveness_score": 5,
            "traffic": 8,
            "noise_level": 5,
            "heat": 4,
            "utility_network_load": 5,
        },
        "downsides": [
            "May increase congestion, noise, and network load.",
            "Needs transport and pedestrian planning to stay balanced.",
        ],
    },
    "add_clinic": {
        "delta": {
            "healthcare_access": 20,
            "social_service_access": 8,
            "livability_score": 8,
            "attractiveness_score": 4,
            "service_capacity": 6,
            "traffic": 3,
        },
        "downsides": [
            "Can increase local traffic and parking demand.",
            "Requires staffing and operational funding.",
        ],
    },
    "add_school": {
        "delta": {
            "education_access": 20,
            "social_service_access": 8,
            "attractiveness_score": 7,
            "livability_score": 6,
            "service_capacity": 5,
            "traffic": 4,
            "utility_network_load": 3,
        },
        "downsides": [
            "School drop-off traffic can rise near peak hours.",
            "Utility and service loads may increase if the zone is already strained.",
        ],
    },
    "add_social_service_center": {
        "delta": {
            "social_service_access": 20,
            "livability_score": 7,
            "service_capacity": 8,
            "attractiveness_score": 4,
            "healthcare_access": 3,
            "education_access": 2,
        },
        "downsides": [
            "Requires steady staffing and program funding.",
        ],
    },
    "upgrade_utilities": {
        "delta": {
            "infrastructure_stability": 18,
            "utility_network_load": -18,
            "service_capacity": 10,
            "environmental_resilience": 10,
            "livability_score": 5,
            "economic_activity": 3,
        },
        "downsides": [
            "Construction phases can temporarily disrupt local activity.",
        ],
    },
    "add_green_roof": {
        "delta": {
            "green_area": 8,
            "heat": -6,
            "eco_score": 7,
            "environmental_resilience": 9,
            "air_quality": 3,
            "attractiveness_score": 4,
            "livability_score": 3,
        },
        "downsides": [
            "Structural suitability and maintenance must be assessed first.",
        ],
    },
    "add_public_square": {
        "delta": {
            "public_space_quality": 16,
            "walkability": 8,
            "attractiveness_score": 10,
            "economic_activity": 4,
            "livability_score": 7,
            "social_service_access": 3,
        },
        "downsides": [
            "Requires active management to avoid underused or poorly maintained space.",
        ],
    },
    "add_playground": {
        "delta": {
            "public_space_quality": 12,
            "livability_score": 7,
            "attractiveness_score": 6,
            "social_service_access": 4,
            "walkability": 3,
        },
        "downsides": [
            "Needs safe placement, maintenance, and supervision planning.",
        ],
    },
    "add_ev_charging": {
        "delta": {
            "environmental_resilience": 7,
            "eco_score": 6,
            "economic_activity": 3,
            "utility_network_load": 4,
            "commercial_access": 2,
            "attractiveness_score": 2,
        },
        "downsides": [
            "Can raise electricity demand if the utility network is already stressed.",
        ],
    },
    "add_water_feature": {
        "delta": {
            "heat": -5,
            "public_space_quality": 8,
            "attractiveness_score": 8,
            "livability_score": 5,
            "green_area": 3,
        },
        "downsides": [
            "Water use, maintenance, and seasonal operation costs increase.",
        ],
    },
    "add_community_center": {
        "delta": {
            "social_service_access": 16,
            "livability_score": 9,
            "attractiveness_score": 6,
            "public_space_quality": 8,
            "service_capacity": 6,
            "employment_support": 3,
        },
        "downsides": [
            "Needs operating budget and program planning to sustain impact.",
        ],
    },
}

IMPROVEMENT_TYPE_TO_ACTION = {
    "park": "add_park",
    "add_park": "add_park",
    "street_light": "add_lighting",
    "lighting": "add_lighting",
    "light": "add_lighting",
    "add_lighting": "add_lighting",
    "bike_lane": "add_bike_lane",
    "add_bike_lane": "add_bike_lane",
    "ramp": "add_ramp",
    "add_ramp": "add_ramp",
    "bus_stop": "add_bus_stop",
    "add_bus_stop": "add_bus_stop",
    "traffic_reduction": "reduce_traffic",
    "reduce_traffic": "reduce_traffic",
    "barrier_removal": "remove_barriers",
    "remove_barriers": "remove_barriers",
    "pedestrian_crossing": "add_pedestrian_crossing",
    "add_pedestrian_crossing": "add_pedestrian_crossing",
    "bench": "add_public_benches",
    "public_bench": "add_public_benches",
    "add_public_benches": "add_public_benches",
    "waste_bin": "add_waste_bins",
    "waste_bins": "add_waste_bins",
    "add_waste_bins": "add_waste_bins",
    "residential_building": "add_residential_building",
    "add_residential_building": "add_residential_building",
    "commercial_building": "add_commercial_building",
    "add_commercial_building": "add_commercial_building",
    "clinic": "add_clinic",
    "add_clinic": "add_clinic",
    "school": "add_school",
    "add_school": "add_school",
    "social_service_center": "add_social_service_center",
    "add_social_service_center": "add_social_service_center",
    "utility_upgrade": "upgrade_utilities",
    "upgrade_utilities": "upgrade_utilities",
    "green_roof": "add_green_roof",
    "add_green_roof": "add_green_roof",
    "public_square": "add_public_square",
    "add_public_square": "add_public_square",
    "playground": "add_playground",
    "add_playground": "add_playground",
    "ev_charging": "add_ev_charging",
    "add_ev_charging": "add_ev_charging",
    "water_feature": "add_water_feature",
    "add_water_feature": "add_water_feature",
    "community_center": "add_community_center",
    "add_community_center": "add_community_center",
}

ACTION_TO_MAP_IMPROVEMENT_TYPE = {
    "add_park": "park",
    "add_lighting": "street_light",
    "add_bike_lane": "bike_lane",
    "add_ramp": "ramp",
    "add_bus_stop": "bus_stop",
    "reduce_traffic": "traffic_reduction",
    "remove_barriers": "barrier_removal",
    "add_pedestrian_crossing": "pedestrian_crossing",
    "add_public_benches": "bench",
    "add_waste_bins": "waste_bin",
    "add_residential_building": "residential_building",
    "add_commercial_building": "commercial_building",
    "add_clinic": "clinic",
    "add_school": "school",
    "add_social_service_center": "social_service_center",
    "upgrade_utilities": "utility_upgrade",
    "add_green_roof": "green_roof",
    "add_public_square": "public_square",
    "add_playground": "playground",
    "add_ev_charging": "ev_charging",
    "add_water_feature": "water_feature",
    "add_community_center": "community_center",
}

DEFAULT_ACTION_ORDER = [
    "add_park",
    "add_lighting",
    "add_ramp",
    "reduce_traffic",
    "add_bike_lane",
    "add_bus_stop",
    "remove_barriers",
    "add_pedestrian_crossing",
    "add_public_benches",
    "add_waste_bins",
    "add_residential_building",
    "add_commercial_building",
    "add_clinic",
    "add_school",
    "add_social_service_center",
    "upgrade_utilities",
    "add_green_roof",
    "add_public_square",
    "add_playground",
    "add_ev_charging",
    "add_water_feature",
    "add_community_center",
]

ZONE_TYPE_WEIGHTS = {
    "residential": {
        "add_park": 1.15,
        "add_lighting": 1.08,
        "add_bike_lane": 1.05,
        "add_ramp": 1.10,
        "add_bus_stop": 1.02,
        "reduce_traffic": 1.10,
        "remove_barriers": 1.08,
        "add_pedestrian_crossing": 1.08,
        "add_public_benches": 1.06,
        "add_waste_bins": 1.02,
        "add_residential_building": 1.12,
        "add_commercial_building": 0.95,
        "add_clinic": 1.06,
        "add_school": 1.04,
        "add_social_service_center": 1.06,
        "upgrade_utilities": 1.08,
        "add_green_roof": 1.06,
        "add_public_square": 1.07,
        "add_playground": 1.08,
        "add_ev_charging": 1.00,
        "add_water_feature": 1.04,
        "add_community_center": 1.08,
    },
    "school": {
        "add_park": 1.08,
        "add_lighting": 1.15,
        "add_bike_lane": 1.00,
        "add_ramp": 1.12,
        "add_bus_stop": 1.05,
        "reduce_traffic": 1.08,
        "remove_barriers": 1.08,
        "add_pedestrian_crossing": 1.18,
        "add_public_benches": 1.02,
        "add_waste_bins": 1.00,
        "add_residential_building": 0.90,
        "add_commercial_building": 0.92,
        "add_clinic": 1.04,
        "add_school": 0.88,
        "add_social_service_center": 1.02,
        "upgrade_utilities": 1.05,
        "add_green_roof": 1.03,
        "add_public_square": 1.04,
        "add_playground": 1.06,
        "add_ev_charging": 0.96,
        "add_water_feature": 1.00,
        "add_community_center": 1.04,
    },
    "commercial": {
        "add_park": 0.96,
        "add_lighting": 1.05,
        "add_bike_lane": 1.08,
        "add_ramp": 1.00,
        "add_bus_stop": 1.10,
        "reduce_traffic": 1.05,
        "remove_barriers": 1.02,
        "add_pedestrian_crossing": 1.08,
        "add_public_benches": 1.00,
        "add_waste_bins": 1.04,
        "add_residential_building": 0.92,
        "add_commercial_building": 1.12,
        "add_clinic": 0.98,
        "add_school": 0.92,
        "add_social_service_center": 0.98,
        "upgrade_utilities": 1.10,
        "add_green_roof": 1.02,
        "add_public_square": 1.08,
        "add_playground": 0.88,
        "add_ev_charging": 1.05,
        "add_water_feature": 1.00,
        "add_community_center": 0.98,
    },
    "road": {
        "add_park": 0.82,
        "add_lighting": 1.20,
        "add_bike_lane": 1.10,
        "add_ramp": 0.95,
        "add_bus_stop": 1.00,
        "reduce_traffic": 1.15,
        "remove_barriers": 0.98,
        "add_pedestrian_crossing": 1.20,
        "add_public_benches": 0.84,
        "add_waste_bins": 0.94,
        "add_residential_building": 0.70,
        "add_commercial_building": 0.88,
        "add_clinic": 0.84,
        "add_school": 0.78,
        "add_social_service_center": 0.86,
        "upgrade_utilities": 1.12,
        "add_green_roof": 0.86,
        "add_public_square": 0.92,
        "add_playground": 0.72,
        "add_ev_charging": 1.02,
        "add_water_feature": 0.84,
        "add_community_center": 0.84,
    },
    "courtyard": {
        "add_park": 1.18,
        "add_lighting": 1.08,
        "add_bike_lane": 0.90,
        "add_ramp": 1.14,
        "add_bus_stop": 0.84,
        "reduce_traffic": 1.00,
        "remove_barriers": 1.14,
        "add_pedestrian_crossing": 0.94,
        "add_public_benches": 1.10,
        "add_waste_bins": 1.02,
        "add_residential_building": 0.95,
        "add_commercial_building": 0.80,
        "add_clinic": 0.96,
        "add_school": 0.92,
        "add_social_service_center": 1.06,
        "upgrade_utilities": 1.10,
        "add_green_roof": 1.04,
        "add_public_square": 1.10,
        "add_playground": 1.12,
        "add_ev_charging": 0.94,
        "add_water_feature": 1.04,
        "add_community_center": 1.10,
    },
    "parkless_courtyard": {
        "add_park": 1.24,
        "add_lighting": 1.08,
        "add_bike_lane": 0.90,
        "add_ramp": 1.14,
        "add_bus_stop": 0.84,
        "reduce_traffic": 1.00,
        "remove_barriers": 1.14,
        "add_pedestrian_crossing": 0.94,
        "add_public_benches": 1.10,
        "add_waste_bins": 1.02,
        "add_residential_building": 0.92,
        "add_commercial_building": 0.80,
        "add_clinic": 0.96,
        "add_school": 0.92,
        "add_social_service_center": 1.06,
        "upgrade_utilities": 1.10,
        "add_green_roof": 1.06,
        "add_public_square": 1.10,
        "add_playground": 1.14,
        "add_ev_charging": 0.92,
        "add_water_feature": 1.06,
        "add_community_center": 1.12,
    },
    "park": {
        "add_park": 0.60,
        "add_lighting": 0.96,
        "add_bike_lane": 0.96,
        "add_ramp": 1.00,
        "add_bus_stop": 0.82,
        "reduce_traffic": 0.90,
        "remove_barriers": 1.04,
        "add_pedestrian_crossing": 0.90,
        "add_public_benches": 1.04,
        "add_waste_bins": 1.05,
        "add_residential_building": 0.40,
        "add_commercial_building": 0.55,
        "add_clinic": 0.72,
        "add_school": 0.68,
        "add_social_service_center": 0.78,
        "upgrade_utilities": 0.92,
        "add_green_roof": 0.82,
        "add_public_square": 1.06,
        "add_playground": 1.08,
        "add_ev_charging": 0.80,
        "add_water_feature": 1.06,
        "add_community_center": 0.96,
    },
    "mixed_use": {
        "add_park": 1.02,
        "add_lighting": 1.08,
        "add_bike_lane": 1.06,
        "add_ramp": 1.04,
        "add_bus_stop": 1.08,
        "reduce_traffic": 1.06,
        "remove_barriers": 1.04,
        "add_pedestrian_crossing": 1.08,
        "add_public_benches": 1.04,
        "add_waste_bins": 1.04,
        "add_residential_building": 1.04,
        "add_commercial_building": 1.06,
        "add_clinic": 1.02,
        "add_school": 1.00,
        "add_social_service_center": 1.04,
        "upgrade_utilities": 1.10,
        "add_green_roof": 1.04,
        "add_public_square": 1.08,
        "add_playground": 1.00,
        "add_ev_charging": 1.04,
        "add_water_feature": 1.02,
        "add_community_center": 1.04,
    },
    "infrastructure": {
        "add_park": 0.80,
        "add_lighting": 1.00,
        "add_bike_lane": 0.90,
        "add_ramp": 0.94,
        "add_bus_stop": 0.92,
        "reduce_traffic": 1.00,
        "remove_barriers": 0.96,
        "add_pedestrian_crossing": 0.94,
        "add_public_benches": 0.80,
        "add_waste_bins": 0.90,
        "add_residential_building": 0.70,
        "add_commercial_building": 0.80,
        "add_clinic": 0.82,
        "add_school": 0.78,
        "add_social_service_center": 0.82,
        "upgrade_utilities": 1.25,
        "add_green_roof": 0.90,
        "add_public_square": 0.84,
        "add_playground": 0.70,
        "add_ev_charging": 1.08,
        "add_water_feature": 0.84,
        "add_community_center": 0.80,
    },
}